routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\PermisosController 	AS Permisos;
use App\Http\Controllers\EmpresasController 	AS Empresas;
use App\Http\Controllers\ModulosController 		AS Modulos;
use App\Http\Controllers\RolesController 		AS Roles;
use App\Http\Controllers\Auth\LoginController	AS Login;
use App\Http\Controllers\UserController 		AS Usuarios;
use App\Http\Controllers\PersonasController 	AS Personas;
use App\Http\Controllers\ReferidoController 	AS Referidos;
use App\Http\Controllers\PreguntasController 	AS Preguntas;
use App\Http\Controllers\BitacorasController 	AS Bitacoras;
use App\Http\Controllers\HomeController			AS Home;






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{provider}', [Login::class, 'redirectToProvider'])->name('social.auth');
Route::get('login/{provider}/callback', [Login::class, 'handleProviderCallback'])->name('social.callback');

Auth::routes();

Route::get('/', function () {
	if(Auth::guest()){
    	return view('auth.login');
	}else{
        return redirect()->route('home')->with('status_success', 'Se ha iniciado sesion recientemente');
	}
});

Route::get('/home', [Home::class, 'index'])->name('home');


/* Perfil */
Route::get('/perfil', [Personas::class, 'perfil'])->name('perfil');
Route::get('/perfil/usuario', [Personas::class, 'perfilUnico'])->name('perfin.usuario');
Route::post('/perfil/store', [Personas::class, 'perfilStore'])->name('perfil.store');



/* Modulo de empresas */
Route::resource('/empresas', Empresas::class)->names('empresas');
Route::get('/empresas/ciudad/{codigo}', [Empresas::class, 'ciudad']);

/* Modulo de permisos */
Route::resource('/permisos', Permisos::class)->names('permisos');

/* Modulo de Roles */
Route::resource('/roles', Roles::class)->names('roles');
Route::get('/asignacion', [Roles::class, 'asignacion'])->name('asignacion');

/* Modulo de Modulos */
Route::resource('/modulos', Modulos::class)->names('modulos');

/*Modulo de Usuarios*/
Route::resource('/usuarios', Usuarios::class)->names('users');

/*Modulo de asignacion de permisos*/
Route::get('/asignacion_permisos/update/{id?}', [Permisos::class, 'edit'])->name('asignacion.edit');
Route::post('/asignacion_permisos/update/permiso/{id?}', [Permisos::class, 'update'])->name('asignacion.update');

/*Modulo de Personas*/
Route::resource('/personas', Personas::class)->names('personas');

/*Modulo de Referidos*/
Route::resource('/referidos', Referidos::class)->names('referidos');

/*Modulo de Tipo Clientes*/
Route::get('/tipo_clientes/{id}', [Referidos::class, 'tipo_clientes']);

/*Modulo de Preguntas*/
Route::resource('/preguntas', Preguntas::class)->names('preguntas');

/*Modulo de bitacoras */
Route::resource('/bitacoras', Bitacoras::class)->names('bitacoras');
Route::get('/generar/{cedula}', [Bitacoras::class, 'generar'])->name('generar');
Route::get('/generar/acciones/{valor}/{bitacora}', [Bitacoras::class, 'acciones'])->name('acciones');
Route::post('/registro/acciones', [Bitacoras::class, 'registro']);
Route::get('/informacion/referido/{cedula}', [Bitacoras::class, 'informacion_referido']);

app/Models/Empresa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
    use HasFactory;

    protected $fillable = [
        'logo_empresa',
        'favicon_empresa',
        'code_tipo_documento',
        'indentificacion_tributaria',
        'nombre_empresa',
        'email_empresa',
        'descripcion_empresa',
        'telefono_principal',
        'telefono_whatsapp',
        'palabras_claves',
        'acerca_de_negocio',
        'codigo_pais',
        'codigo_departamento',
        'codigo_ciudad',
        'codigo_postal',
        'direccion_empresa',
        'estado_empresa',
    ];
}

app/Http/Controllers/EmpresasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\AddyPaise AS Paises;
use App\Models\AddyCiudade AS Ciudades;
use App\Models\Empresa;
use Illuminate\Support\Facades\Crypt;
use Storage;
use File;

class EmpresasController extends Controller {

    public function index() {
        $empresas = Empresa::all();
        return view('pages.empresas.index', compact('empresas'));
    }

    public function create() {
        $paises = Paises::all();
        return view('pages.empresas.create', compact('paises'));
    }

    public function store(Request $request) {

        $rules = [
            'logo_empresa' => 'required|mimes:jpg,jpeg,bmp,png|max:5000',
            'favicon_empresa' => 'mimes:jpg,jpeg,png|max:5000',
            'code_tipo_documento' => 'required|integer',
            'indentificacion_tributaria' => 'required|integer|unique:empresas,indentificacion_tributaria',
            'nombre_empresa' => 'required',
            'email_empresa' => 'required|email|unique:empresas,email_empresa',
            'descripcion_empresa' => 'required',
            'telefono_whatsapp' => 'required',
            'codigo_pais' => 'required',
            'codigo_ciudad' => 'required',
            'direccion_empresa' => 'required',
            'estado_empresa' => 'required|integer',
        ];


        $messages = [
            'logo_empresa.required' => 'Agregue un logo de la empresa',
            'logo_empresa.mimes' => 'El campo logo debe ser un archivo de imagen (jpg, jpeg, png)',
            'code_tipo_documento.required' => 'Seleccione un tipo de documento.',
            'indentificacion_tributaria.required' => 'Por favor, digite el número de su NIT/CC',
            'indentificacion_tributaria.unique' => 'La identificación de la empresa ya se encuentra registrada.',
            'nombre_empresa.required' => 'El nombre de la empresa es obligatorio.',
            'email_empresa.required' => 'El correo electrónico es obligatorio.',
            'email_empresa.email' => 'El correo electrónico es inválido.',
            'descripcion_empresa.required' => 'La descripción de la empresa es obligatoria.',
            'telefono_whatsapp.required' => 'El número de whatsapp es obligatorio.',
            'codigo_pais.required' => 'El campo País es obligatorio.',
            'codigo_ciudad.required' => 'El campo Ciudad es obligatorio.',
            'direccion_empresa.required' => 'Proporcione una dirección de la empresa.',
            'estado_empresa.required' => 'El estado de la empresa es obligatorio.',
        ];

        $this->validate($request, $rules, $messages);

        $directorio = 'empresas/' . $request->indentificacion_tributaria;
        
        if (!File::exists($directorio)) {
            Storage::makeDirectory($directorio);
        }
        
        $logo = $request->file('logo_empresa')->store($directorio);
        
        if (empty($request->favicon_empresa)) {
            $favicon = '';
        } else {
            /* carga del logo al proyecto */
            $favicon = $request->file('favicon_empresa')->store($directorio);
            /* FIn carga del logo al proyecto */
        }
        
        $palabras_claves = implode(",", $request->palabras_claves);
        
        Empresa::create([
            'logo_empresa' => $logo,
            'favicon_empresa' => $favicon,
            'code_tipo_documento' => $request->code_tipo_documento,
            'indentificacion_tributaria' => $request->indentificacion_tributaria,
            'nombre_empresa' => $request->nombre_empresa,
            'email_empresa' => $request->email_empresa,
            'descripcion_empresa' => $request->descripcion_empresa,
            'telefono_principal' => $request->telefono_fijo,
            'telefono_whatsapp' => Crypt::encryptString($request->telefono_whatsapp),
            'palabras_claves' => $palabras_claves,
            'acerca_de_negocio' => $request->acerca_negocio,
            'codigo_pais' => $request->codigo_pais,
            'codigo_departamento' => $request->codigo_ciudad,
            'codigo_ciudad' => $request->codigo_ciudad,
            'codigo_postal' => $request->codigo_postal,
            'direccion_empresa' => $request->direccion_empresa,
            'estado_empresa' => $request->estado_empresa
        ]);

        return redirect()->route('empresas.index')->with('status_success', 'Se ha registrado la empresa en nuestro sitema');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {

        $empresa = Empresa::where('id', '=', $id)->get();

        $pais = Paises::where('codigo', '=', $empresa[0]->codigo_pais)->get();
        $ciudad = Ciudades::where('id_ciudades', $empresa[0]->codigo_ciudad)->get();
        $palabras_claves = explode(',', $empresa[0]->palabras_claves);


        return view('pages.empresas.show', compact('empresa', 'pais', 'ciudad', 'palabras_claves'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $empresa = Empresa::where('id', '=', $id)->get();

        $paises = Paises::all();
        $ciudad = Ciudades::where('id_ciudades', $empresa[0]->codigo_ciudad)->get();
        $palabras_claves = explode(',', $empresa[0]->palabras_claves);

        return view('pages.empresas.edit', compact('empresa', 'paises', 'ciudad', 'palabras_claves'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $rules = [
            'code_tipo_documento' => 'required|integer',
            'indentificacion_tributaria' => 'required',
            'nombre_empresa' => 'required',
            'email_empresa' => 'required|email',
            'descripcion_empresa' => 'required',
            'telefono_whatsapp' => 'required',
            'codigo_pais' => 'required',
            'codigo_ciudad' => 'required',
            'direccion_empresa' => 'required',
            'estado_empresa' => 'required|integer',
        ];


        $messages = [
            'code_tipo_documento.required' => 'Seleccione un tipo de documento.',
            'indentificacion_tributaria.required' => 'Por favor, digite el número de su NIT/CC',
            'indentificacion_tributaria.unique' => 'La identificación de la empresa ya se encuentra registrada.',
            'nombre_empresa.required' => 'El nombre de la empresa es obligatorio.',
            'email_empresa.required' => 'El correo electrónico es obligatorio.',
            'email_empresa.email' => 'El correo electrónico es inválido.',
            'descripcion_empresa.required' => 'La descripción de la empresa es obligatoria.',
            'telefono_whatsapp.required' => 'El número de whatsapp es obligatorio.',
            'codigo_pais.required' => 'El campo País es obligatorio.',
            'codigo_ciudad.required' => 'El campo Ciudad es obligatorio.',
            'direccion_empresa.required' => 'Proporcione una dirección de la empresa.',
            'estado_empresa.required' => 'El estado de la empresa es obligatorio.',
        ];

        $this->validate($request, $rules, $messages);

        $directorio = 'empresas/' . $id;

        if (!File::exists($directorio)) {
            Storage::makeDirectory($directorio);
        }

        if (empty($request->logo_empresa)) {
            $logo = $request->imagen_bd_logo;
        } else {
            /* carga del logo al proyecto */
            $logo = $request->file('logo_empresa')->store($directorio);
            /* FIn carga del logo al proyecto */
        }

        if (empty($request->favicon_empresa)) {
            $favicon = $request->imagen_fv_bd;
        } else {
            /* carga del logo al proyecto */
            $favicon = $request->file('favicon_empresa')->store($directorio);
            /* FIn carga del logo al proyecto */
        }
        $palabras_claves = implode(",", $request->palabras_claves);
        Empresa::where('indentificacion_tributaria', $id)
                ->update([
                    'logo_empresa' => $logo,
                    'favicon_empresa' => $favicon,
                    'code_tipo_documento' => $request->code_tipo_documento,
                    'nombre_empresa' => $request->nombre_empresa,
                    'email_empresa' => $request->email_empresa,
                    'descripcion_empresa' => $request->descripcion_empresa,
                    'telefono_principal' => $request->telefono_fijo,
                    'telefono_whatsapp' => Crypt::encryptString($request->telefono_whatsapp),
                    'palabras_claves' => $palabras_claves,
                    'acerca_de_negocio' => $request->acerca_negocio,
                    'codigo_pais' => $request->codigo_pais,
                    'codigo_departamento' => $request->codigo_ciudad,
                    'codigo_ciudad' => $request->codigo_ciudad,
                    'codigo_postal' => $request->codigo_postal,
                    'direccion_empresa' => $request->direccion_empresa,
                    'estado_empresa' => $request->estado_empresa
        ]);

        return redirect()->route('empresas.index')->with('status_success', 'Actualización exitosa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        
    }

    public function ciudad($id) {
        $ciudades = Ciudades::where('codigo_pais', $id)->get();
        return view('pages.empresas.ciudades', compact('ciudades'));
    }

}

resources/views/pages/empresas/ciudades.blade.php
@foreach($ciudades as $ciudad)
    <option value="{{ $ciudad->id_ciudades }}">{{ $ciudad->nombre_ciudad }}</option>
@endforeach

resources/views/pages/empresas/create.blade.php
@extends('layouts.app')

@section('title', 'Registro Empresa - Aplicativo Addy')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <section id="dashboard-ecommerce">
            @include('pages.configuracion.mensajes.alertas')
            <div class="row match-height">
                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <h3>Registro de una empresa</h3>
                            <p class="card-text font-small-3">Bienvenido, desde esta sección puedes crear una nueva Empresa en Addy</p>
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>

                            <form id="form_empresa" action="{{ route('empresas.store') }}" method="POST" enctype="multipart/form-data">

                                @csrf
                                @method('POST')

                                <div class="form-group">
                                    <label><b>(*) </b>Logo de la empresa</label>
                                    <input class='form-control' type="file" id="logo" name="logo_empresa"  value="{{ old('logo_empresa') }}">
                                </div>

                                <div class="form-group">
                                    <label><b>(*) </b>Favicon Empresa</label>
                                    <input class='form-control' type="file" id="favicon" name="favicon_empresa"  value="{{ old('favicon_empresa') }}">
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-3">
                                            <label><b>(*) </b>Tipo de Identificación:</label>
                                            <select class="form-control"  name="code_tipo_documento" >
                                                <option value=""></option>
                                                <option value="1">CC</option>
                                                <option value="2">NIT</option>
                                                <option value="3">RUT</option>
                                            </select>
                                        </div>
                                        <div class="col-7">
                                            <label><b>(*) </b>Número de Identificación:</label>
                                            <input type="text" class="form-control" name="indentificacion_tributaria" value="{{ old('indentificacion_tributaria') }}" id="nro_identificacion" >
                                        </div>
                                        <div class="col-2">
                                            <label><b>(*) </b>No. de verificación:</label>
                                            <input type="text" class="form-control" name="digito_verificacion" readonly=""  value="{{ old('digito_verificacion') }}" id="digito_verificacion" >
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label><b>(*) </b>Razón social:</label>
                                    <input type="text" class="form-control" name="nombre_empresa"  value="{{ old('nombre_empresa') }}">
                                </div>

                                <div class="form-group">
                                    <label><b>(*) </b>Email empresa:</label>
                                    <input type="email" class="form-control" name="email_empresa" id="email"  value="{{ old('email_empresa') }}">
                                    <code id="error-email" style="display: none;">Debes de digitar un correo válido.</code>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label>Descripción de la empresa:</label>
                                            <textarea class="form-control" name="descripcion_empresa" >{{ old('descripcion_empresa') }}</textarea>
                                        </div>
                                        <div class="col">
                                            <label>Acerca de su negocio:</label>
                                            <textarea class="form-control" name="acerca_negocio"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label>Teléfono fijo:</label>
                                            <input class='form-control' type="number" name="telefono_fijo"  value="{{ old('telefono_fijo') }}">
                                        </div>
                                        <div class="col">
                                            <label>WhatsApp:</label><br>
                                            <input class='form-control' type="tel" name="telefono_whatsapp" id="celular_movil" value="{{ old('telefono_whatsapp') }}">
                                            <span id="valid-msg" class="hide">✓ Válido</span>
                                            <span id="error-msg" class="hide"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label>Dirección de la empresa:</label>
                                            <input class="form-control" type="text" name="direccion_empresa"  value="{{ old('direccion_empresa') }}">
                                        </div>
                                        <div class="col">
                                            <label>Código Postal:</label>
                                            <input class="form-control" type="number" name="codigo_postal"  value="{{ old('codigo_postal') }}">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>Palabras claves:</label>
                                    <select class="form-control palabras_claves" multiple="multiple" name="palabras_claves[]">

                                    </select>  
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label>País de la empresa:</label>
                                            <select class="form-control" id="selector"  name="codigo_pais" value="{{ old('codigo_pais') }}">
                                                <option value="" selected=""></option>
                                                @foreach($paises as $pais)
                                                <option value="{{ $pais->codigo }}">{{ $pais->pais }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="col">
                                            <label>Ciudad de la empresa:</label>
                                            <select class="form-control" id="selector_ciudad"  name="codigo_ciudad" value="{{ old('codigo_ciudad') }}">
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>Estado de la Empresa:</label>
                                    <select class="form-control" name="estado_empresa" value="{{ old('estado_empresa') }}">
                                        <option value="">Seleccione un estado</option>
                                        <option value="1">Activo</option>
                                        <option value="2">Inactivo</option>
                                    </select>
                                </div>
                                <center>
                                    <button type="submit" class="btn btn-primary" id="registro_empresa">Registrar Empresa</button>
                                </center>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
@endsection

resources/views/pages/empresas/index.blade.php
@extends('layouts.app')

@section('title', 'Módulo Empresas - Addy')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <section id="dashboard-ecommerce">
            <div class="row match-height">
                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <h3>Empresas en el aplicativo Addy</h3>
                            <p class="card-text font-small-3">Hola! acá verás un listado con todas las empresas registradas.</p>
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>
                            <div class="panel-busqueda">
                                <div class="row">
                                    <div class="form-group col-12 col-md-9 col-lg-9 col-sm-9 col-xl-9 col-lg-9">
                                        <label><b>Búsqueda de empresas:</b></label>
                                        <input type="text" class="form-control" name="busqueda_empresa" id="busqueda" data-modulo="empresas">
                                    </div>
                                    <div class="form-group col-12 col-md-3 col-lg-3 col-sm-3 col-xl-3 col-lg-3">
                                        <label></label>
                                        <button class="btn btn-primary btn-block waves-effect waves-float waves-light" tabindex="4">Búsqueda avanzada</button>
                                    </div>
                                </div>
                                <table class="table table-bordered table-hover table-responsive ">
                                    <thead>
                                        <tr>
                                            <th>NIT / CC</th>
                                            <th>Logo</th>
                                            <th>Razón Social</th>
                                            <th>Celular de contacto</th>
                                            <th colspan="4" style="text-align: center;">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($empresas as $empresa)
                                        <tr>
                                            <td>{{ $empresa->indentificacion_tributaria }}</td>
                                            <td><img src="{{ asset('/storage/app/'.$empresa->logo_empresa) }}" width="100px"></td>
                                            <td>{{ $empresa->nombre_empresa}}</td>
                                            <td>{{ Crypt::decryptString($empresa->telefono_whatsapp) }}</td>
                                            <td>
                                                <button type="button" class="btn btn-success informacion" data-href="{{ route('empresas.show', $empresa->id) }}"> 
                                                    Ver
                                                </button>
                                            </td>
                                            <td>
                                                <a href="{{ route('empresas.edit', $empresa->id) }}">
                                                    <button type="button" class="btn btn-info"> 
                                                        Editar 
                                                    </button>
                                                </a>
                                            </td>

                                            <td>
                                                <button type="button" class="btn btn-danger eliminar" data-href="{{ route('empresas.destroy', $empresa->id) }}"> 
                                                    Eliminar
                                                </button>
                                            </td>

                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
    </div>
</div>

@include('pages.configuracion.mensajes.modales')

@endsection