routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\PermisosController 	AS Permisos;
use App\Http\Controllers\EmpresasController 	AS Empresas;
use App\Http\Controllers\ModulosController 		AS Modulos;
use App\Http\Controllers\RolesController 		AS Roles;
use App\Http\Controllers\Auth\LoginController	AS Login;
use App\Http\Controllers\UserController 		AS Usuarios;
use App\Http\Controllers\PersonasController 	AS Personas;
use App\Http\Controllers\ReferidoController 	AS Referidos;
use App\Http\Controllers\PreguntasController 	AS Preguntas;
use App\Http\Controllers\BitacorasController 	AS Bitacoras;
use App\Http\Controllers\HomeController			AS Home;






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{provider}', [Login::class, 'redirectToProvider'])->name('social.auth');
Route::get('login/{provider}/callback', [Login::class, 'handleProviderCallback'])->name('social.callback');

Auth::routes();

Route::get('/', function () {
	if(Auth::guest()){
    	return view('auth.login');
	}else{
        return redirect()->route('home')->with('status_success', 'Se ha iniciado sesion recientemente');
	}
});

Route::get('/home', [Home::class, 'index'])->name('home');


/* Perfil */
Route::get('/perfil', [Personas::class, 'perfil'])->name('perfil');
Route::get('/perfil/usuario', [Personas::class, 'perfilUnico'])->name('perfin.usuario');
Route::post('/perfil/store', [Personas::class, 'perfilStore'])->name('perfil.store');



/* Modulo de empresas */
Route::resource('/empresas', Empresas::class)->names('empresas');
Route::get('/empresas/ciudad/{codigo}', [Empresas::class, 'ciudad']);

/* Modulo de permisos */
Route::resource('/permisos', Permisos::class)->names('permisos');

/* Modulo de Roles */
Route::resource('/roles', Roles::class)->names('roles');
Route::get('/asignacion', [Roles::class, 'asignacion'])->name('asignacion');

/* Modulo de Modulos */
Route::resource('/modulos', Modulos::class)->names('modulos');

/*Modulo de Usuarios*/
Route::resource('/usuarios', Usuarios::class)->names('users');

/*Modulo de asignacion de permisos*/
Route::get('/asignacion_permisos/update/{id?}', [Permisos::class, 'edit'])->name('asignacion.edit');
Route::post('/asignacion_permisos/update/permiso/{id?}', [Permisos::class, 'update'])->name('asignacion.update');

/*Modulo de Personas*/
Route::resource('/personas', Personas::class)->names('personas');

/*Modulo de Referidos*/
Route::resource('/referidos', Referidos::class)->names('referidos');

/*Modulo de Tipo Clientes*/
Route::get('/tipo_clientes/{id}', [Referidos::class, 'tipo_clientes']);

/*Modulo de Preguntas*/
Route::resource('/preguntas', Preguntas::class)->names('preguntas');

/*Modulo de bitacoras */
Route::resource('/bitacoras', Bitacoras::class)->names('bitacoras');
Route::get('/generar/{cedula}', [Bitacoras::class, 'generar'])->name('generar');
Route::get('/generar/acciones/{valor}/{bitacora}', [Bitacoras::class, 'acciones'])->name('acciones');
Route::post('/registro/acciones', [Bitacoras::class, 'registro']);
Route::get('/informacion/referido/{cedula}', [Bitacoras::class, 'informacion_referido']);

resources/views/layouts/sections/menu-vertical.blade.php
<ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
    <li class="nav-item">

        <a class="d-flex align-items-center opcion-administrador" href="{{ url('home') }}">
            <i data-feather="home"></i>
            <span class="menu-title text-truncate" id="titulo_principal" data-i18n="Dashboards">
                Administrador
            </span>
            <span class="badge badge-light-warning badge-pill ml-auto mr-1">?</span>
        </a>

        <div class="opcion_adicional"></div>

        <ul class="menu-content">
            @can('haveaccess','permisos.habilitado.empresas')
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{{ route('permisos.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">
                        Empresas
                    </span>
                </a>
                <ul class="menu-content">
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('empresas.index') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="Preview">
                                Listado
                            </span>
                        </a>
                    </li>
                    @can('haveaccess','permisos.crear.empresas')
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('empresas.create') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="List">
                                Registrar Empresa
                            </span>
                        </a>
                    </li>
                    @endcan
                </ul>
            </li>
            @endcan
<!--
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{{ route('permisos.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">
                        Permisos
                    </span>
                </a>
                <ul class="menu-content">
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('permisos.index') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="Preview">
                                Listado
                            </span>
                        </a>
                    </li>
                    <li>
                        <a class="d-flex align-items-center" href="app-invoice-list.html">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="List">
                                Crear permiso
                            </span>
                        </a>
                    </li>
                </ul>
            </li>
-->
            @can('haveaccess','permisos.habilitado.modulos')
            <li class="nav-item">
                <a class="d-flex align-items-center" href="#">
                    <i data-feather="circle"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">
                        M&oacute;dulos
                    </span>
                </a>
                <ul class="menu-content">
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('modulos.index') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="Preview">
                                Listado
                            </span>
                        </a>
                    </li>
                    @can('haveaccess','permisos.crear.modulos')
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('modulos.create') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="List">
                                Crear m&oacute;dulo
                            </span>
                        </a>
                    </li>
                    @endcan
                </ul>
            </li>
            @endcan
            @can('haveaccess','permisos.habilitado.roles')
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{{ route('permisos.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">
                        Roles
                    </span>
                </a>
                <ul class="menu-content">
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('roles.index') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="Preview">
                                Listado
                            </span>
                        </a>
                    </li>
                    @can('haveaccess','permisos.crear.roles')
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('roles.create') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="List">
                                Crear rol
                            </span>
                        </a>
                    </li>
                    @endcan
                </ul>
            </li>
            @endcan
            @can('haveaccess','permisos.habilitado.usuarios')
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{{ route('users.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">
                        Usuarios
                    </span>
                </a>
                <ul class="menu-content">
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('users.index') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="Preview">
                                Listado
                            </span>
                        </a>
                    </li>
                    @can('haveaccess','permisos.crear.usuarios')
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('users.create') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="List">
                                Crear Usuario
                            </span>
                        </a>
                    </li>
                    @endcan
                </ul>
            </li>
            @endcan
            @can('haveaccess','permisos.habilitado.preguntas')
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{{ route('permisos.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">
                        Preguntas
                    </span>
                </a>
                <ul class="menu-content">
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('preguntas.index') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="Preview">
                                Listado
                            </span>
                        </a>
                    </li>
                    @can('haveaccess','permisos.crear.preguntas')
                    <li>
                        <a class="d-flex align-items-center" href="{{ route('preguntas.create') }}">
                            <i data-feather="circle"></i>
                            <span class="menu-item text-truncate" data-i18n="List">
                                Registrar preguntas
                            </span>
                        </a>
                    </li>
                    @endcan
                </ul>
            </li>
            @endcan
        </ul>
    </li>
    <!-- Demas opciones de los usuarios -->                
    <li class=" navigation-header">
        <span data-i18n="Apps &amp; Pages">
            OPCIONES GENERALES
        </span>
        <i data-feather="more-horizontal"></i>
    </li>
    @can('haveaccess','permisos.habilitado.personas')
    <li class="nav-item">
        <a class="d-flex align-items-center" href="{{ route('personas.index') }}">
            <i data-feather="user"></i>
            <span class="menu-title text-truncate" data-i18n="Invoice">
                Módulo Personas
            </span>
        </a>
        <ul class="menu-content">
            <li>
                <a class="d-flex align-items-center" href="{{ route('personas.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-item text-truncate" data-i18n="Preview">
                        Listado
                    </span>
                </a>
            </li>
            @can('haveaccess','permisos.crear.personas')
            <li>
                <a class="d-flex align-items-center" href="{{ route('personas.create') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-item text-truncate" data-i18n="List">
                        Registrar Persona
                    </span>
                </a>
            </li>
            @endcan
        </ul>
    </li>
    @endcan
    @can('haveaccess','permisos.habilitado.referidos')
    <li class="nav-item">
        <a class="d-flex align-items-center" href="{{ route('referidos.index') }}">
            <i data-feather="user"></i>
            <span class="menu-title text-truncate" data-i18n="Invoice">
                Módulo Referidos
            </span>
        </a>
        <ul class="menu-content">
            <li>
                <a class="d-flex align-items-center" href="{{ route('referidos.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-item text-truncate" data-i18n="Preview">
                        Listado
                    </span>
                </a>
            </li>
            @can('haveaccess','permisos.crear.referidos')
            <li>
                <a class="d-flex align-items-center" href="{{ route('referidos.create') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-item text-truncate" data-i18n="List">
                        Registrar Referido
                    </span>
                </a>
            </li>
            @endcan
        </ul>
    </li>
    @endcan
    @can('haveaccess','permisos.habilitado.bitacoras')
    <li class="nav-item">
        <a class="d-flex align-items-center" href="{{ route('bitacoras.index') }}">
            <i data-feather="user"></i>
            <span class="menu-title text-truncate" data-i18n="Invoice">
                Módulo Bitacoras
            </span>
        </a>
        <ul class="menu-content">
            <li>
                <a class="d-flex align-items-center" href="{{ route('bitacoras.index') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-item text-truncate" data-i18n="Preview">
                        Listado
                    </span>
                </a>
            </li>
            @can('haveaccess','permisos.crear.bitacoras')
            <li>
                <a class="d-flex align-items-center" href="{{ route('bitacoras.create') }}">
                    <i data-feather="circle"></i>
                    <span class="menu-item text-truncate" data-i18n="List">
                        Crear Bitacora
                    </span>
                </a>
            </li>
            @endcan
        </ul>
    </li>
    @endcan
    
</ul>