routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\PermisosController 	AS Permisos;
use App\Http\Controllers\EmpresasController 	AS Empresas;
use App\Http\Controllers\ModulosController 		AS Modulos;
use App\Http\Controllers\RolesController 		AS Roles;
use App\Http\Controllers\Auth\LoginController	AS Login;
use App\Http\Controllers\UserController 		AS Usuarios;
use App\Http\Controllers\PersonasController 	AS Personas;
use App\Http\Controllers\ReferidoController 	AS Referidos;
use App\Http\Controllers\PreguntasController 	AS Preguntas;
use App\Http\Controllers\BitacorasController 	AS Bitacoras;
use App\Http\Controllers\HomeController			AS Home;






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{provider}', [Login::class, 'redirectToProvider'])->name('social.auth');
Route::get('login/{provider}/callback', [Login::class, 'handleProviderCallback'])->name('social.callback');

Auth::routes();

Route::get('/', function () {
	if(Auth::guest()){
    	return view('auth.login');
	}else{
        return redirect()->route('home')->with('status_success', 'Se ha iniciado sesion recientemente');
	}
});

Route::get('/home', [Home::class, 'index'])->name('home');


/* Perfil */
Route::get('/perfil', [Personas::class, 'perfil'])->name('perfil');
Route::get('/perfil/usuario', [Personas::class, 'perfilUnico'])->name('perfin.usuario');
Route::post('/perfil/store', [Personas::class, 'perfilStore'])->name('perfil.store');



/* Modulo de empresas */
Route::resource('/empresas', Empresas::class)->names('empresas');
Route::get('/empresas/ciudad/{codigo}', [Empresas::class, 'ciudad']);

/* Modulo de permisos */
Route::resource('/permisos', Permisos::class)->names('permisos');

/* Modulo de Roles */
Route::resource('/roles', Roles::class)->names('roles');
Route::get('/asignacion', [Roles::class, 'asignacion'])->name('asignacion');

/* Modulo de Modulos */
Route::resource('/modulos', Modulos::class)->names('modulos');

/*Modulo de Usuarios*/
Route::resource('/usuarios', Usuarios::class)->names('users');

/*Modulo de asignacion de permisos*/
Route::get('/asignacion_permisos/update/{id?}', [Permisos::class, 'edit'])->name('asignacion.edit');
Route::post('/asignacion_permisos/update/permiso/{id?}', [Permisos::class, 'update'])->name('asignacion.update');

/*Modulo de Personas*/
Route::resource('/personas', Personas::class)->names('personas');

/*Modulo de Referidos*/
Route::resource('/referidos', Referidos::class)->names('referidos');

/*Modulo de Tipo Clientes*/
Route::get('/tipo_clientes/{id}', [Referidos::class, 'tipo_clientes']);

/*Modulo de Preguntas*/
Route::resource('/preguntas', Preguntas::class)->names('preguntas');

/*Modulo de bitacoras */
Route::resource('/bitacoras', Bitacoras::class)->names('bitacoras');
Route::get('/generar/{cedula}', [Bitacoras::class, 'generar'])->name('generar');
Route::get('/generar/acciones/{valor}/{bitacora}', [Bitacoras::class, 'acciones'])->name('acciones');
Route::post('/registro/acciones', [Bitacoras::class, 'registro']);
Route::get('/informacion/referido/{cedula}', [Bitacoras::class, 'informacion_referido']);

app/Http/Controllers/ModulosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\AddyModulo AS Modulos;
use App\Models\Empresa;
use App\Permisos\Models\Permission AS Permisos;
use App\Permisos\Models\Role;
use DB;
use Illuminate\Support\Facades\Crypt;

class ModulosController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        $modulos = Modulos::all();

        return view('pages.modulos.index', compact('modulos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $empresas = Empresa::all();
        return view('pages.modulos.create', compact('empresas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $rules = [
            'icon_modulo'       => 'required',
            'nombre_modulo'     => 'required',
            'slug_modulo'       => 'required|unique:addy_modulos,slug_modulo',
            'seccion_modulo'    => 'required',
            'estado_modulo'     => 'required',
        ];


        $messages = [
            'icon_modulo.required'      => 'Agregue un icono del módulo.',
            'nombre_modulo.required'    => 'Debes especificar el nombre del módulo.',
            'slug_modulo.required'      => 'El slug del módulo es importante.',
            'slug_modulo.unique'        => 'El slug del Modulo ya se encuentra registrado, verifica e intenta nuevamente.',
            'seccion_modulo.required'   => 'Por favor, seleccione la sección del módulo.',
            'estado_modulo.required'    => 'Seleccione el estado del Módulo a crear.',
        ];

        $this->validate($request, $rules, $messages);


        Modulos::create([
            'icon_modulo' => $request->icon_modulo,
            'nombre_modulo' => $request->nombre_modulo,
            'descripcion_modulo' => $request->descripcion_modulo,
            'slug_modulo' => $request->slug_modulo,
            'seccion_id' => $request->seccion_modulo,
            'estado_id' => $request->estado_modulo,
        ]);

        if($request->permisos){
            foreach ($request->permisos as $value) {
               Permisos::create([
                    'name'          => $value." ".strtolower($request->slug_modulo),
                    'slug'          => "permisos.".$value.".".strtolower($request->slug_modulo),
                    'description'   => "El usuario podra ".$value." ".strtolower($request->slug_modulo),
                    'name_module'   => strtolower($request->slug_modulo)
                ]);
            }
        }

        if ($request->empresa_modulo) {

            $info_modulo = Modulos::all()->last();

            foreach ($request->empresa_modulo as $empresa) {
                DB::table('addy_detalle_modulos_empresas')->insert([
                    'empresa_id'    => $empresa,
                    'modulo_id'     => $info_modulo['id_modulo']
                ]);
            }

            return redirect()->route('modulos.index')->with('status_success', 'Se ha registrado el módulo en nuestro sistema.');
        } else {
            return "NO HAY";
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $modulo = Modulos::where('id_modulo', $id)->get();

        return view("pages.modulos.show", compact('modulo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {

        $empresas_del_modulo = [];

        $empresas = Empresa::all();
        $modulo = Modulos::where('id_modulo', $id)->get();

        $modulos_empresas = DB::table('addy_detalle_modulos_empresas')
                ->select('addy_detalle_modulos_empresas.*', 'addy_modulos.*', 'empresas.id AS id_empresa')
                ->join('addy_modulos', 'addy_detalle_modulos_empresas.modulo_id', '=', 'addy_modulos.id_modulo')
                ->join('empresas', 'addy_detalle_modulos_empresas.empresa_id', '=', 'empresas.id')
                ->where('id_modulo', $id)
                ->get();

        foreach ($modulos_empresas as $mod) {
            $empresas_del_modulo[] = $mod->empresa_id;
        }

        return view("pages.modulos.edit", compact('modulo', 'empresas', 'empresas_del_modulo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        
        $rules = [
            'icon_modulo'       => 'required',
            'nombre_modulo'     => 'required',
            'seccion_modulo'    => 'required',
            'estado_modulo'     => 'required',
        ];
        
        $messages = [
            'icon_modulo.required'      => 'Agregue un icono del módulo.',
            'nombre_modulo.required'    => 'Debes especificar el nombre del módulo.',
            'seccion_modulo.required'   => 'Por favor, seleccione la sección del módulo.',
            'estado_modulo.required'    => 'Seleccione el estado del Módulo a crear.',
        ];
        
        $this->validate($request, $rules, $messages);
        
        $resultado = Modulos::where('slug_modulo', $request->slug_modulo)->count();
        
        Modulos::where('id_modulo', $id)
                ->update([
                    'icon_modulo'           => $request->icon_modulo,
                    'nombre_modulo'         => $request->nombre_modulo,
                    'descripcion_modulo'    => $request->descripcion_modulo,
                    'seccion_id'            => $request->seccion_modulo,
                    'estado_id'             => $request->estado_modulo
        ]);

        DB::table('addy_detalle_modulos_empresas')->where('modulo_id', '=', $id)->delete();

        foreach ($request->empresa_modulo as $empresa) {
            DB::table('addy_detalle_modulos_empresas')->insert([
                'empresa_id'    => $empresa,
                'modulo_id'     => $id
            ]);
        }

        return true;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }


    public function generar_permisos(Request $request){

    }
}

resources/views/pages/modulos/create.blade.php
@extends('layouts.app')

@section('title', 'Registro Modulo - Aplicativo Addy')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <section id="dashboard-ecommerce">
            
            <div class="row match-height">

                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    @include('pages.configuracion.mensajes.alertas')
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <h3>Registro de una Módulo</h3>
                            <p class="card-text font-small-3">
                            Bienvenido, desde esta sección puedes crear una nuevo Módulo en Addy</p>
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>

                            <form id="form_empresa" action="{{ route('modulos.store') }}" method="POST">

                                @csrf
                                @method('POST')

                                <div class="form-group">
                                    <label><b>(*) </b>Icono del Módulo <a href="" title="¿Por qué debo colocar esto?"><i data-feather="help-circle"></i></a></label>
                                    <input class='form-control' type="text" name="icon_modulo"  value="{{ old('icon_modulo') }}">
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label><b>(*) </b>Nombre del módulo:</label>
                                            <input type="text" class="form-control" name="nombre_modulo" value="{{ old('nombre_modulo') }}" >
                                        </div>
                                        <div class="col">
                                            <label><b>(*) </b>Slug del Módulo:</label>
                                            <input type="text" class="form-control" name="slug_modulo" value="{{ old('slug_modulo') }}">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label><b>(*) </b>Descripción del Módulo:</label>
                                    <textarea class="form-control" name="descripcion_modulo">{{ old('descripcion_modulo') }}</textarea>                                    
                                </div>

                                <div class="form-group">
                                    <label>Asignar módulo a la empresa:</label>
                                    <select class="form-control" name="empresa_modulo[]" value="{{ old('estado_empresa') }}" id="selector_empresa" multiple="multiple">
                                        @foreach($empresas as $empresa)
                                            <option value="{{ $empresa->id }}">{{ $empresa->indentificacion_tributaria }} - {{ $empresa->nombre_empresa }}</option>
                                        @endforeach
                                    </select>                                   
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label><b>(*) </b>Sección del Módulo:</label>
                                            <select class="form-control" name="seccion_modulo" value="{{ old('estado_empresa') }}">
                                                <option value="">Seleccione un estado</option>
                                                <option value="1">APPS & PAGES</option>
                                                <option value="2">USER INTERFACE</option>
                                            </select>
                                        </div>
                                        <div class="col">
                                             <label><b>(*) </b>Estado de lal Módulo:</label>
                                            <select class="form-control" name="estado_modulo" value="{{ old('estado_empresa') }}">
                                                <option value="">Seleccione un estado</option>
                                                <option value="1">Activo</option>
                                                <option value="2">Inactivo</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label><b>(*) </b>Permisos habilitados del Módulo:</label>
                                    <select class="form-control" name="permisos[]" value="{{ old('estado_empresa') }}" id="selector_permisos" multiple="multiple">
                                        <option value="habilitado" selected="">Activar Modulo</option>
                                        <option value="crear">Crear</option>
                                        <option value="editar">Editar</option>
                                        <option value="ver">Ver</option>
                                        <option value="eliminar">Eliminar</option>
                                    </select>
                                </div>


                                <center>
                                    <button type="submit" class="btn btn-primary" id="registro_empresa">Registrar Módulo</button>
                                </center>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
@endsection

resources/views/pages/modulos/edit.blade.php
{!! Form::open(['id' => 'formulario', 'route' => array('modulos.update', $modulo[0]->id_modulo), 'files' => false]) !!}

@csrf
@method('PUT')

<div class="form-group">
    <label><b>(*) </b>Icono del Módulo <a href="" title="¿Por qué debo colocar esto?"><i data-feather="help-circle"></i></a></label>
    <input class='form-control' type="text" name="icon_modulo"  value="{{ $modulo[0]['icon_modulo'] }}">
</div>

<div class="form-group">
    <div class="row">
        <div class="col">
            <label><b>(*) </b>Nombre del módulo:</label>
            <input type="text" class="form-control" name="nombre_modulo" value="{{ $modulo[0]['nombre_modulo'] }}" >
        </div>
        <div class="col">
            <label><b>(*) </b>Slug del Módulo:</label>
            <input type="text" class="form-control" value="{{ $modulo[0]['slug_modulo'] }}" disabled="">
        </div>
    </div>
</div>

<div class="form-group">
    <label><b>(*) </b>Descripción del Módulo:</label>
    <textarea class="form-control" name="descripcion_modulo">{{ $modulo[0]['descripcion_modulo'] }}</textarea>                                    
</div>

<div class="form-group">
    <label>Asignar módulo a la empresa:</label>
    <select class="form-control" name="empresa_modulo[]" value="{{ old('estado_empresa') }}" id="selector_empresa" multiple="multiple">
        @foreach($empresas as $empresa)
        @if (is_array($empresas_del_modulo) && in_array($empresa->id, $empresas_del_modulo)) { ?>
        <option value="{{ $empresa->id }}" selected="">{{ $empresa->indentificacion_tributaria }} - {{ $empresa->nombre_empresa }}</option>
        @else
        <option value="{{ $empresa->id }}">{{ $empresa->indentificacion_tributaria }} - {{ $empresa->nombre_empresa }}</option>
        @endif
        @endforeach
    </select>                                   
</div>

<div class="form-group">
    <div class="row">
        <div class="col">
            <label><b>(*) </b>Sección del Módulo:</label>
            <select class="form-control" name="seccion_modulo" value="{{ old('estado_empresa') }}">
                <option value="">Seleccione un estado</option>
                @if($modulo[0]->seccion_id == '1')
                    <option value="1" selected="">APPS & PAGES</option>
                    <option value="2">USER INTERFACE</option>
                @else
                    <option value="1">APPS & PAGES</option>
                    <option value="2" selected="">USER INTERFACE</option>
                @endif
            </select>
        </div>
        <div class="col">
            <label><b>(*) </b>Estado de lal Módulo:</label>
            <select class="form-control" name="estado_modulo" value="{{ old('estado_empresa') }}">
                <option value="">Seleccione un estado</option>
                @if($modulo[0]->estado_id == '1')
                <option value="1" selected="">Activo</option>
                <option value="2">Inactivo</option>
                @else
                <option value="1">Activo</option>
                <option value="2" selected="">Inactivo</option>
                @endif
            </select>
        </div>
    </div>
</div>

{!! Form::close() !!}

<script>
    $("#selector").select2();
    $("#selector_ciudad").select2();
    $("#selector_empresa").select2();
</script>

resources/views/pages/modulos/index.blade.php
@extends('layouts.app')

@section('title', 'Módulos Addy')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <section id="dashboard-ecommerce">
            <div class="row match-height">
                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <h3>Modulos del aplicativo</h3>
                            <p class="card-text font-small-3">Hola! acá verás un listado con todas las empresas registradas.</p>
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>

                            <div class="panel-busqueda">
                                <div class="row">
                                    <div class="form-group col-12 col-md-9 col-lg-9 col-sm-9 col-xl-9 col-lg-9">
                                        <label><b>Búsqueda de M&oacute;dulos:</b></label>
                                        <input type="text" class="form-control" name="busqueda_empresa" id="busqueda" data-modulo="empresas">
                                    </div>
                                    <div class="form-group col-12 col-md-3 col-lg-3 col-sm-3 col-xl-3 col-lg-3">
                                        <label></label>
                                        <button class="btn btn-primary btn-block waves-effect waves-float waves-light" tabindex="4">Búsqueda avanzada</button>
                                    </div>
                                </div>
                                <table class="table table-bordered table-responsive ">
                                    <thead>
                                        <tr>
                                            <th>ID M&oacute;dulo</th>
                                            <th>Icon / Imagen del M&oacute;dulo</th>
                                            <th>Nombre del M&oacute;dulo</th>
                                            <th>Ruta &uacute;nica del M&oacute;dulo</th>
                                            <th colspan="4" style="text-align: center;">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($modulos as $modulo)

                                        @if($modulo->estado_id != 1)
                                        <tr class="alert alert-danger">
                                            <td>{{ $modulo->id_modulo }}</td>
                                            <td><i data-feather="{{ $modulo->icon_modulo }}"></i></td>
                                            <td>{{ $modulo->nombre_modulo }}</td>
                                            <td>{{ $modulo->slug_modulo }}</td>
                                            <td>
                                                <button type="button" class="btn btn-success informacion" data-href="{{ route('modulos.show', $modulo->id_modulo) }}"> 
                                                    Ver
                                                </button>
                                            </td>
                                            <td>
                                                <button type="button" class="btn btn-info edicion" data-href="{{ route('modulos.edit', $modulo->id_modulo) }}"> 
                                                    Editar 
                                                </button>
                                            </td>

                                            <td>
                                                <button type="button" class="btn btn-danger eliminar" data-href="{{ route('empresas.destroy', $modulo->id_modulo) }}"> 
                                                    Eliminar
                                                </button>
                                            </td>
                                        </tr>
                                        @else
                                        <tr>
                                            <td>{{ $modulo->id_modulo }}</td>
                                            <td><i data-feather="{{ $modulo->icon_modulo }}"></i></td>
                                            <td>{{ $modulo->nombre_modulo }}</td>
                                            <td>{{ $modulo->slug_modulo }}</td>
                                            <td>
                                                <button type="button" class="btn btn-success informacion" data-href="{{ route('modulos.show', $modulo->id_modulo) }}"> 
                                                    Ver
                                                </button>
                                            </td>
                                            <td>
                                                <button type="button" class="btn btn-info edicion" data-href="{{ route('modulos.edit', $modulo->id_modulo) }}"> 
                                                    Editar 
                                                </button>
                                            </td>

                                            <td>
                                                <button type="button" class="btn btn-danger eliminar" data-href="{{ route('modulos.destroy', $modulo->id_modulo) }}"> 
                                                    Eliminar
                                                </button>
                                            </td>
                                        </tr>
                                        @endif
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
    </div>
</div>

@include('pages.configuracion.mensajes.modales')

@endsection

resources/views/pages/modulos/show.blade.php
<div class="form-group">
    <label><b>Icono del M&odblac;dulo: </b></label>
    <i data-feather="{{ $modulo[0]['icon_modulo'] }}"></i>
</div>

<div class="form-group">
    <label><b>Nombre del M&oacute;dulo: </b></label>
    <input type="text" class="form-control" value="{{ $modulo[0]['nombre_modulo'] }}" readonly="">
</div>

<div class="form-group">
    <label><b>Descripción del M&oacute;dulo: </b></label>
    <textarea class="form-control" readonly="">{{ $modulo[0]['descripcion_modulo'] }}</textarea>
</div>

<div class="form-group">
    <label><b>Slug del M&oacute;dulo: </b></label>
    <textarea class="form-control" readonly="">{{ $modulo[0]['slug_modulo'] }}</textarea>
</div>

<div class="form-group">
    <label><b>Sección del Módulo: </b></label>
    <select class="form-control" disabled="">
        @if($modulo[0]['slug_modulo'] == 1)
        <option value="1" selected="">APPS & PAGES</option>
        <option value="2">USER INTERFACE</option>
        @else
        <option value="1">APPS & PAGES</option>
        <option value="2" selected="">USER INTERFACE</option>
        @endif
    </select>
</div>


<div class="form-group">
    <label><b>Estado del M&oacute;dulo: </b></label>
    @if($modulo[0]['estado_id'] == 1)
    <input class="form-control" type="text" value="Activo" readonly="">                   
    @else
    <input class="form-control" type="text" value="Inactivo">                   
    @endif
</div>