routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\PermisosController 	AS Permisos;
use App\Http\Controllers\EmpresasController 	AS Empresas;
use App\Http\Controllers\ModulosController 		AS Modulos;
use App\Http\Controllers\RolesController 		AS Roles;
use App\Http\Controllers\Auth\LoginController	AS Login;
use App\Http\Controllers\UserController 		AS Usuarios;
use App\Http\Controllers\PersonasController 	AS Personas;
use App\Http\Controllers\ReferidoController 	AS Referidos;
use App\Http\Controllers\PreguntasController 	AS Preguntas;
use App\Http\Controllers\BitacorasController 	AS Bitacoras;
use App\Http\Controllers\HomeController			AS Home;






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login/{provider}', [Login::class, 'redirectToProvider'])->name('social.auth');
Route::get('login/{provider}/callback', [Login::class, 'handleProviderCallback'])->name('social.callback');

Auth::routes();

Route::get('/', function () {
	if(Auth::guest()){
    	return view('auth.login');
	}else{
        return redirect()->route('home')->with('status_success', 'Se ha iniciado sesion recientemente');
	}
});

Route::get('/home', [Home::class, 'index'])->name('home');


/* Perfil */
Route::get('/perfil', [Personas::class, 'perfil'])->name('perfil');
Route::get('/perfil/usuario', [Personas::class, 'perfilUnico'])->name('perfin.usuario');
Route::post('/perfil/store', [Personas::class, 'perfilStore'])->name('perfil.store');



/* Modulo de empresas */
Route::resource('/empresas', Empresas::class)->names('empresas');
Route::get('/empresas/ciudad/{codigo}', [Empresas::class, 'ciudad']);

/* Modulo de permisos */
Route::resource('/permisos', Permisos::class)->names('permisos');

/* Modulo de Roles */
Route::resource('/roles', Roles::class)->names('roles');
Route::get('/asignacion', [Roles::class, 'asignacion'])->name('asignacion');

/* Modulo de Modulos */
Route::resource('/modulos', Modulos::class)->names('modulos');

/*Modulo de Usuarios*/
Route::resource('/usuarios', Usuarios::class)->names('users');

/*Modulo de asignacion de permisos*/
Route::get('/asignacion_permisos/update/{id?}', [Permisos::class, 'edit'])->name('asignacion.edit');
Route::post('/asignacion_permisos/update/permiso/{id?}', [Permisos::class, 'update'])->name('asignacion.update');

/*Modulo de Personas*/
Route::resource('/personas', Personas::class)->names('personas');

/*Modulo de Referidos*/
Route::resource('/referidos', Referidos::class)->names('referidos');

/*Modulo de Tipo Clientes*/
Route::get('/tipo_clientes/{id}', [Referidos::class, 'tipo_clientes']);

/*Modulo de Preguntas*/
Route::resource('/preguntas', Preguntas::class)->names('preguntas');

/*Modulo de bitacoras */
Route::resource('/bitacoras', Bitacoras::class)->names('bitacoras');
Route::get('/generar/{cedula}', [Bitacoras::class, 'generar'])->name('generar');
Route::get('/generar/acciones/{valor}/{bitacora}', [Bitacoras::class, 'acciones'])->name('acciones');
Route::post('/registro/acciones', [Bitacoras::class, 'registro']);
Route::get('/informacion/referido/{cedula}', [Bitacoras::class, 'informacion_referido']);

app/Http/Controllers/PreguntasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Empresa      AS Empresas;
use App\Models\AddyModulo   AS Modulos;
use App\Models\AddyPregunta AS Preguntas;

use Gate;

class PreguntasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $empresas   = Empresas::all();
        $modulos    = Modulos::all();
        $preguntas  = Preguntas::all();

        return view('pages.configuracion.preguntas.index', compact('empresas', 'modulos', 'preguntas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $empresas   = Empresas::all();
        $modulos    = Modulos::all();

        return view('pages.configuracion.preguntas.create', compact('empresas', 'modulos'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('haveaccess','permisos.crear.preguntas');

        $rules = [
            'pregunta'   => 'required',
            'empresas'   => 'required',
            'modulo'     => 'required',
            'estado'     => 'required',
        ];
        
        $messages = [
            'pregunta.required'     => 'La descripción de la pregunta es importante.',
            'empresas.required'     => 'Seleccione una empresa para la pregunta.',
            'modulo.required'       => 'Seleccione un módulo para la pregunta.',
            'estado.required'       => 'El estado para la pregunta es importante.',
        ];

        $this->validate($request, $rules, $messages);
        $fecha = date('Y-m-d');
        Preguntas::create([
            'descripcion_preguntas' => $request->pregunta,
            'id_modulo'             => $request->modulo,
            'id_opcional'           => $request->codigo_opcional,
            'id_empresa'            => $request->empresas,
            'fecha_pregunta'        => $fecha,
            'nombre_usuario'        => auth()->user()->name,
            'estado_pregunta'       => $request->estado,
        ]);

        return redirect()->route('preguntas.create')->with('status_success', 'Se ha registrado la pregunta en nuestro sitema');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Gate::authorize('haveaccess','permisos.editar.preguntas');

        $pregunta   = Preguntas::where('id', $id)->get();
        $empresas   = Empresas::all();
        $modulos    = Modulos::all();

        return view('pages.configuracion.preguntas.edit', compact('empresas', 'modulos', 'pregunta'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Gate::authorize('haveaccess','permisos.editar.preguntas');

        $rules = [
            'pregunta'   => 'required',
            'empresas'   => 'required',
            'modulo'     => 'required',
            'estado'     => 'required',
        ];
        
        $messages = [
            'pregunta.required'     => 'La descripción de la pregunta es importante.',
            'empresas.required'     => 'Seleccione una empresa para la pregunta.',
            'modulo.required'       => 'Seleccione un módulo para la pregunta.',
            'estado.required'       => 'El estado para la pregunta es importante.',
        ];

        $this->validate($request, $rules, $messages);

        $pregunta   = Preguntas::where('id', $id)
                        ->update([
                            'descripcion_preguntas' => $request->pregunta,
                            'id_empresa'            => $request->empresas,
                            'id_modulo'             => $request->modulo,
                            'id_opcional'           => $request->codigo_opcional,
                            'estado_pregunta'       => $request->estado,
                        ]);
        
        return true;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/configuracion/preguntas/create.blade.php
@extends('layouts.app')

@section('title', 'Registro Preguntas - Aplicativo Addy')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <section id="dashboard-ecommerce">

            @include('pages.configuracion.mensajes.modales')
            @include('pages.configuracion.mensajes.alertas')
            
            <div class="row match-height">
                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <h3>Registro de preguntas</h3>
                            <p class="card-text font-small-3">
                                Bienvenido, desde esta sección puedes crear una nuevo Módulo en Addy</p>
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>
                            
                            <form action="{{ route('preguntas.store') }}" method="POST">

                                @csrf
                                @method('POST')

                                <div class="form-group">
                                	<label><b>(*) Nombre usuario:</b></label>
                                	<input type="text" class="form-control" value="{{ auth()->user()->name }}" disabled="">
                                </div>

                                <div class="form-group">
                                	<label><b>(*) Descripción de la Pregunta:</b></label>
                                	<input type="text" class="form-control" name="pregunta" value="{{ old('pregunta') }}" >
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label><b>(*) Asignar a la empresa:</b></label>
                                            <select class="form-control" name="empresas" id="selector_empresa">
                                                <option value="" selected=""></option>
                                                @foreach($empresas as $empresa)
                                                <option value="{{ $empresa->indentificacion_tributaria }}">{{ $empresa->indentificacion_tributaria }} - {{ $empresa->nombre_empresa }}</option>
                                                @endforeach
                                            </select>  
                                        </div>
                                        <div class="col">
                                            <label><b>(*) Asignar pregunta al Módulo: </b></label>
                                            <select class="form-control" name="modulo" id="selector">
                                            	<option value="" selected=""></option>
                                                @foreach($modulos as $modulo)
                                                	<option value="{{ $modulo->slug_modulo }}">{{ $modulo->nombre_modulo }}</option>
                                                @endforeach
                                            </select> 
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col">
                                            <label><b></b>Código opcional: </label>
                                    		<input type="text" class="form-control" name="codigo_opcional">
                                        </div>
                                        <div class="col">
                                            <label><b>(*) Fecha: </b></label>
                                    		<input type="date" class="form-control" value="{{ date('Y-m-d') }}" disabled="">
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>Estado de la Pregunta:</label>
                                    <select class="form-control" name="estado" value="{{ old('estado_empresa') }}">
                                        <option value="" selected="">Seleccione un estado</option>
                                        <option value="1">Activo</option>
                                        <option value="2">Inactivo</option>
                                    </select>
                                </div>
                                <br>
                                <center>
                                    <button type="submit" class="btn btn-primary">Registrar y volver</button>
                                </center>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

@endsection

resources/views/pages/configuracion/preguntas/edit.blade.php
{!! Form::open(['id' => 'formulario', 'route' => array('preguntas.update', $pregunta[0]->id), 'files' => false]) !!}

@csrf
@method('PUT')

<div class="form-group">
	<label><b>(*) Nombre usuario:</b></label>
	<input type="text" class="form-control" value="{{ $pregunta[0]->nombre_usuario }}" readonly="">
</div>

<div class="form-group">
	<label><b>(*) Descripción de la Pregunta:</b></label>
	<input type="text" class="form-control" name="pregunta" value="{{ $pregunta[0]->descripcion_preguntas }}" >
</div>

<div class="form-group">
	<label><b>ID Opcional:</b></label>
	<input type="text" class="form-control" name="codigo_opcional" value="{{ $pregunta[0]->id_opcional }}" >
</div>

<div class="form-group">
	<label><b>(*) Asignar a la empresa:</b></label>
	<select class="form-control" name="empresas" id="selector_empresa">
		@foreach($empresas as $empresa)
			@if($pregunta[0]->id_empresa == $empresa->indentificacion_tributaria)
				<option value="{{ $empresa->indentificacion_tributaria }}" selected="">{{ $empresa->indentificacion_tributaria }} - {{ $empresa->nombre_empresa }}</option>
			@else
				<option value="{{ $empresa->indentificacion_tributaria }}">{{ $empresa->indentificacion_tributaria }} - {{ $empresa->nombre_empresa }}</option>
			@endif
		@endforeach
	</select>  
</div>

<div class="form-group">
	<label><b>(*) Asignar pregunta al Módulo: </b></label>
	<select class="form-control" name="modulo" id="selector">
		@foreach($modulos as $modulo)
			@if($pregunta[0]->id_modulo == $modulo->slug_modulo)
				<option value="{{ $modulo->slug_modulo }}" selected="">{{ $modulo->nombre_modulo }}</option>
			@else
				<option value="{{ $modulo->slug_modulo }}">{{ $modulo->nombre_modulo }}</option>
			@endif
		@endforeach
	</select> 
</div>

<div class="form-group">
	<label><b></b>Fecha registro: </label>
	<input type="date" class="form-control" value="{{ $pregunta[0]->fecha_pregunta }}">
</div>


<div class="form-group">
	<label>Estado de la Pregunta:</label>
	<select class="form-control" name="estado">
		@if($pregunta[0]->estado_pregunta == 1)
		<option value="1" selected="">Activo</option>
		<option value="2">Inactivo</option>
		@else
		<option value="1">Activo</option>
		<option value="2" selected="">Inactivo</option>
		@endif
	</select>
</div>

{!! Form::close() !!}

<script>
    $("#selector").select2();
    $("#selector_empresa").select2();
</script>

resources/views/pages/configuracion/preguntas/index.blade.php
@extends('layouts.app')

@section('title', 'Módulo Preguntas - Addy')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">
        <section id="dashboard-ecommerce">
            <div class="row match-height">
                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <h3>Empresas en el aplicativo Addy</h3>
                            <p class="card-text font-small-3">Hola! acá verás un listado con todas las empresas registradas.</p>
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>
                            <div class="panel-busqueda">
                                <div class="row">
                                    <div class="form-group col-12 col-md-9 col-lg-9 col-sm-9 col-xl-9 col-lg-9">
                                        <label><b>Búsqueda de empresas:</b></label>
                                        <input type="text" class="form-control" name="busqueda_empresa" id="busqueda" data-modulo="empresas">
                                    </div>
                                    <div class="form-group col-12 col-md-3 col-lg-3 col-sm-3 col-xl-3 col-lg-3">
                                        <label></label>
                                        <button class="btn btn-primary btn-block waves-effect waves-float waves-light" tabindex="4">Búsqueda avanzada</button>
                                    </div>
                                </div>
                                <table class="table table-bordered table-hover table-responsive ">
                                    <thead>
                                        <tr>
                                            <th>Descripción pregunta</th>
                                            <th>Módulo</th>
                                            <th>NIT Empresa</th>
                                            <th>Usuario creador</th>
                                            <th>Fecha pregunta</th>
                                            <th colspan="4" style="text-align: center;">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($preguntas as $pregunta)
                                        <tr>
                                            <td>{{ $pregunta->descripcion_preguntas }}</td>
                                            <td>{{ $pregunta->id_modulo}}</td>
                                            <td>{{ $pregunta->id_empresa }}</td>
                                            <td>{{ $pregunta->nombre_usuario }}</td>
                                            <td>{{ $pregunta->fecha_pregunta }}</td>
                                            <!--
                                            <td>
                                                <button type="button" class="btn btn-success informacion" data-href=""> 
                                                    Ver
                                                </button>
                                            </td>-->
                                            <td>
                                            	<button type="button" class="btn btn-info edicion" data-href="{{ route('preguntas.edit', $pregunta->id) }}"> 
                                                	Editar 
                                            	</button>
                                            </td>

                                            <td>
                                                <button type="button" class="btn btn-danger eliminar" data-href="{{ route('preguntas.destroy', $pregunta->id) }}"> 
                                                    Eliminar
                                                </button>
                                            </td>

                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
        </section>
    </div>
</div>

@include('pages.configuracion.mensajes.modales')

@endsection

resources/views/pages/configuracion/preguntas/show.blade.php
show.blade.php